export const timelineData = [
  {
    year: "2024 — Foundation",
    title: "HTML & CSS Fundamentals",
    desc: "Learned semantic HTML5 structure, CSS box model, Flexbox, and basic responsive layouts. Built my first static websites.",
    tags: ["HTML5", "CSS3", "Flexbox"],
    completed: true,
    initial: { opacity: 0, x: -100 },
    whileInView: { opacity: 1, x: 0 },
  },
  {
    year: "2024 — Core",
    title: "JavaScript Fundamentals",
    desc: "Mastered variables, functions, arrays, objects, DOM manipulation, and event-driven programming.",
    tags: ["JavaScript", "DOM API", "Events"],
    completed: true,
    initial: { opacity: 0, x: 100 },
    whileInView: { opacity: 1, x: 0 },
  },
  {
    year: "2025 — Deep Dive",
    title: "Advanced JavaScript",
    desc: "Explored closures, prototypes, async/await, Promises, ES modules, and design patterns.",
    tags: ["ES2022+", "Async/Await", "OOP"],
    completed: true,
    initial: { opacity: 0, x: -100 },
    whileInView: { opacity: 1, x: 0 },
  },
  {
    year: "2025 — Type Safety",
    title: "TypeScript",
    desc: "Adopted TypeScript for scalable codebases. Learned strict typing, generics, enums.",
    tags: ["TypeScript", "Generics", "Interfaces"],
    completed: true,
    initial: { opacity: 0, x: 100 },
    whileInView: { opacity: 1, x: 0 },
  },
  {
    year: "2025 — Framework",
    title: "React & Next",
    desc: "Built component-driven UIs with hooks, context API, custom hooks.",
    tags: ["React 18", "Hooks", "Zustand"],
    completed: true,
    initial: { opacity: 0, x: -100 },
    whileInView: { opacity: 1, x: 0 },
  },
  {
    year: "2026–Now — Horizon",
    title: "Full-Stack Development",
    desc: "Currently expanding into back-end with Node.js, Express, PostgreSQL, and Prisma.",
    tags: ["Node.js", "PostgreSQL", "Prisma"],
    completed: false,
    initial: { opacity: 0, x: 100 },
    whileInView: { opacity: 1, x: 0 },
  },
];
